//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication.ServicePerson {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/ServicePerson")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePerson.IServicePerson")]
    public interface IServicePerson {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePerson/GetPerson", ReplyAction="http://tempuri.org/IServicePerson/GetPersonResponse")]
        ClientApplication.ServicePerson.Person GetPerson(int Id, string Auth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePerson/GetPerson", ReplyAction="http://tempuri.org/IServicePerson/GetPersonResponse")]
        System.Threading.Tasks.Task<ClientApplication.ServicePerson.Person> GetPersonAsync(int Id, string Auth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePerson/SavePerson", ReplyAction="http://tempuri.org/IServicePerson/SavePersonResponse")]
        void SavePerson(ClientApplication.ServicePerson.Person person, string Auth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePerson/SavePerson", ReplyAction="http://tempuri.org/IServicePerson/SavePersonResponse")]
        System.Threading.Tasks.Task SavePersonAsync(ClientApplication.ServicePerson.Person person, string Auth);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePersonChannel : ClientApplication.ServicePerson.IServicePerson, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePersonClient : System.ServiceModel.ClientBase<ClientApplication.ServicePerson.IServicePerson>, ClientApplication.ServicePerson.IServicePerson {
        
        public ServicePersonClient() {
        }
        
        public ServicePersonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePersonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePersonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePersonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientApplication.ServicePerson.Person GetPerson(int Id, string Auth) {
            return base.Channel.GetPerson(Id, Auth);
        }
        
        public System.Threading.Tasks.Task<ClientApplication.ServicePerson.Person> GetPersonAsync(int Id, string Auth) {
            return base.Channel.GetPersonAsync(Id, Auth);
        }
        
        public void SavePerson(ClientApplication.ServicePerson.Person person, string Auth) {
            base.Channel.SavePerson(person, Auth);
        }
        
        public System.Threading.Tasks.Task SavePersonAsync(ClientApplication.ServicePerson.Person person, string Auth) {
            return base.Channel.SavePersonAsync(person, Auth);
        }
    }
}
